# Generated by Django 2.0.13 on 2021-07-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='title',
            field=models.TextField(default='test title'),
        ),
    ]
