# Generated by Django 2.0.13 on 2021-07-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_requests_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='title',
            field=models.CharField(default='test title', max_length=400),
        ),
    ]
