# Generated by Django 2.0.13 on 2021-07-30 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0004_auto_20210730_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coworkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=400)),
                ('phone_number', models.CharField(default='XXX-XXXX-XXXX', max_length=13)),
                ('email', models.CharField(default='xxx@xxx.xxx', max_length=100)),
                ('portfolio_url', models.URLField(default=' ')),
                ('coworker_id', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_url', models.URLField(default=' ')),
                ('submitted_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('coworker_id', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='requests',
            name='coworker',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requests',
            name='company',
            field=models.CharField(max_length=400),
        ),
    ]
