# Generated by Django 2.0.13 on 2021-07-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_introduce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduce',
            old_name='contents',
            new_name='contents1',
        ),
        migrations.RenameField(
            model_name='introduce',
            old_name='title',
            new_name='title_big',
        ),
        migrations.AddField(
            model_name='introduce',
            name='contents2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='introduce',
            name='image_url1',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='introduce',
            name='image_url2',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='introduce',
            name='title_small1',
            field=models.CharField(default='test title1', max_length=400),
        ),
        migrations.AddField(
            model_name='introduce',
            name='title_small2',
            field=models.CharField(default='test title2', max_length=400),
        ),
    ]
