# Generated by Django 2.0.13 on 2021-07-30 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0007_auto_20210731_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coworkers',
            new_name='Coworker',
        ),
        migrations.RenameModel(
            old_name='Portfolios',
            new_name='Portfolio',
        ),
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
