# Generated by Django 2.0.13 on 2021-07-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20210731_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduce',
            name='image_url2',
        ),
        migrations.AlterField(
            model_name='introduce',
            name='image_url1',
            field=models.ImageField(upload_to=''),
        ),
    ]
