# Generated by Django 2.0.13 on 2021-07-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20210731_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='제목', max_length=400)),
                ('contents', models.TextField(blank=True)),
                ('image', models.FileField(default='static/management/fruit.jpg', upload_to='')),
            ],
        ),
    ]
