# Generated by Django 2.0.13 on 2021-07-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='contents',
            new_name='contents1',
        ),
        migrations.AddField(
            model_name='banner',
            name='contents2',
            field=models.TextField(blank=True),
        ),
    ]
