# Generated by Django 2.0.13 on 2021-07-31 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20210731_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='coworker_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='coworker',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='coworker_name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='management.Coworker'),
        ),
        migrations.AddField(
            model_name='request',
            name='coworker_name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='management.Coworker'),
        ),
        migrations.AlterField(
            model_name='coworker',
            name='coworker_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
