# Generated by Django 2.0.13 on 2021-07-31 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20210731_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='coworker_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Coworker'),
        ),
        migrations.AlterField(
            model_name='request',
            name='coworker_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Coworker'),
        ),
    ]
