# Generated by Django 2.0.13 on 2021-08-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20210731_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_url',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video_contents',
            field=models.FileField(default='static/management/video/test.mp4', upload_to=''),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(default='static/management/image/fruit.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='introduce',
            name='image1',
            field=models.FileField(default='static/management/image/orange.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='introduce',
            name='image2',
            field=models.FileField(default='static/management/image/orange.svg', upload_to=''),
        ),
    ]
