# Generated by Django 2.0.13 on 2021-08-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20210806_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
