# Generated by Django 2.0.13 on 2021-08-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_portfolio_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='video_contents',
            field=models.FileField(default='/media/video/test.mp4', upload_to=''),
        ),
    ]
