# Generated by Django 2.0.13 on 2021-08-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_auto_20210806_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='video_contents',
            field=models.FileField(default='settings.MEDIA_ROOT/video/test.mp4', storage='/home/dev/devproject/media', upload_to='video'),
        ),
    ]
