# Generated by Django 2.0.13 on 2021-08-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_auto_20210806_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Introduce1',
        ),
        migrations.RenameModel(
            old_name='Introduce',
            new_name='Introduce2',
        ),
    ]
