# Generated by Django 2.0.13 on 2021-08-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_auto_20210806_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(default='image/image01.jpg', upload_to='')),
                ('image2', models.FileField(default='image/image02.jpg', upload_to='')),
                ('image3', models.FileField(default='image/image03.jpg', upload_to='')),
                ('image4', models.FileField(default='image/image04.jpg', upload_to='')),
            ],
        ),
    ]
