# Generated by Django 2.0.13 on 2021-08-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='title',
        ),
        migrations.RemoveField(
            model_name='request',
            name='video_contents',
        ),
        migrations.AddField(
            model_name='request',
            name='budget',
            field=models.TextField(blank=True),
        ),
    ]
